server.port=${APPOINTMENTS_SERVER_PORT}
spring.application.name=${APPOINTMENTS_SPRING_APPLICATION_NAME}

#spring.profiles.active=dev
spring.mvc.pathmatch.matching-strategy=${SPRING_MVC_PATHMATCH_MATCHING_STRATEGY:ant_path_matcher}

openmrs.username=${OPENMRS_USERNAME}
openmrs.password=${OPENMRS_PASSWORD}
openmrs.url=${OPENMRS_URL}


## Keycloak Config
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.resource=${KEYCLOAK_RESOURCE}
keycloak.realm=${KEYCLOAK_REALM}
app.keycloak.client-secret=${APP_KEYCLOAK_CLIENT_SECRET}
keycloak.use-resource-role-mappings=${KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS:true}
#The line below will prevent redirect to login page
keycloak.bearer-only=${KEYCLOAK_BEARER_ONLY:true}
keycloak.disable-trust-manager=${KEYCLOAK_DISABLE_TRUST_MANAGER:true}


openmrs.timeslots=${OPENMRS_TIMESLOTS}
openmrs.types=${OPENMRS_TYPES}
openmrs.book=${OPENMRS_BOOK}
openmrs.slot=${OPENMRS_SLOT}

openmrs.appointment=${OPENMRS_APPOINTMENT}
openmrs.schedule=${OPENMRS_SCHEDULE}
openmrs.apps=${OPENMRS_APPS}
openmrs.visits=${OPENMRS_VISITS}


spring.security.oauth2.client.registration.articles-client-oidc.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_ARTICLES_CLIENT_OIDC_CLIENT_ID:appointments-client}
spring.security.oauth2.client.provider.spring.issuer-uri=${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPRING_ISSUER_URI:http://localhost:8083}

#authentication = https://172.105.157.130/auths
#notification = https://172.105.157.130/notification

authentication=${AUTHENTICATION_SERVICE_URL}
notification=${NOTIFICATION_SERVICE_URL}

spring.codec.max-in-memory-size=${SPRING_CODEC_MAX_IN_MEMORY_SIZE:100MB}
