server.port=8082
spring.application.name=botswanaappointments

#spring.profiles.active=dev
spring.mvc.pathmatch.matching-strategy = ant_path_matcher

openmrs.username = dev
openmrs.password = Bemr@123
openmrs.url = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/


## Keycloak Config
keycloak.auth-server-url =http://keycloak:8080/
keycloak.resource =botswana-emr
keycloak.realm =botswana-emr-realm
app.keycloak.client-secret=LtpCwXs8J2YHxEAFN2hc2sI6CfLHPNjB
keycloak.use-resource-role-mappings = true
#The line below will prevent redirect to login page
keycloak.bearer-only = true
keycloak.disable-trust-manager=true


openmrs.timeslots = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/timeslot?v=default
openmrs.types = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/appointmenttype?v=default
openmrs.book = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/appointmentallowingoverbook
openmrs.slot = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/timeslot/

openmrs.appointment = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/appointmentrequest
openmrs.schedule = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/appointment
openmrs.apps = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/v1/appointmentscheduling/appointment?v=default


spring.security.oauth2.client.registration.articles-client-oidc.client-id=appointments-client
spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:8083

#authentication = https://botswanaemrdev.intellisoftkenya.com/auths
#notification = https://botswanaemrdev.intellisoftkenya.com/notification

authentication =http://172.105.157.130:8081/auths
notification = http://172.105.157.130:7001/notification

spring.codec.max-in-memory-size=100MB
