version: "3.5"
services:
  botswana_emr_auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: dnjau/botswana_emr_auth_image:latest
    container_name: botswanaauth
    env_file:
      - .env.${ENV_PROFILE:-server}   # Picks dev or server based on ENV_PROFILE
    command: bash -c "java -jar ./botswana_emr_auth_javabackend/BotswanaEMRAuthentication-0.0.1-SNAPSHOT.jar"
    ports:
      - "${SERVER_PORT:-8081}:8081"
    volumes:
      - .:/botswana_emr_auth_javabackend
    networks:
      - emr-network

networks:
  emr-network:
    driver: bridge