server.port=${AUTH_SERVER_PORT}
spring.application.name=${AUTH_SPRING_APPLICATION_NAME}


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=${AUTH_SPRING_DATASOURCE_URL}
spring.datasource.username=${AUTH_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${AUTH_SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=${AUTH_SPRING_JPA_SHOW_SQL:true}
spring.datasource.hikari.maximum-pool-size=${AUTH_SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:5}
spring.datasource.hikari.minimum-idle=${AUTH_SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}





