server.port=8081
spring.application.name=botswanaauth

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://0.0.0.0:5455/authentication}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:intellisoft}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true







