spring.profiles.active=server

openmrs.username = dev
openmrs.password = Bemr@123
openmrs.url = http://botswanaemrdemo.intellisoftkenya.com:9901/openmrs/ws/rest/

#mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=botswanaemr@gmail.com
spring.mail.password=zvwmevsebljjnawy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Keycloak

keycloak.public-client= true

keycloak.ssl-required = external
app.keycloak.grant-type=password
app.keycloak.scope=openid, profile

keycloak.auth-server-url =http://keycloak:8080/
keycloak.resource=botswana-emr
keycloak.realm=botswana-emr-realm
app.keycloak.client-id=${keycloak.resource}
app.keycloak.client-secret=LtpCwXs8J2YHxEAFN2hc2sI6CfLHPNjB
app.keycloak.authServerUrl=http://keycloak:8080/

app.keycloak.refresh=/realms/botswana-emr-realm/protocol/openid-connect/token

app.keycloak.realm.username=admin
app.keycloak.realm.password=adminpass

keycloak.confidential-port=443

keycloak.use-resource-role-mappings = true
#The line below will prevent redirect to login page
keycloak.bearer-only = true

server.error.include-message=always

keycloak.disable-trust-manager=true

notification = http://172.105.157.130:7001/notification
#notification = http://0.0.0.0:7001/