spring.profiles.active=${SPRING_PROFILES_ACTIVE:server}

openmrs.username=${OPENMRS_USERNAME}
openmrs.password=${OPENMRS_PASSWORD}
openmrs.url=${OPENMRS_URL}

#mail sender
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

#Keycloak
keycloak.public-client=${KEYCLOAK_PUBLIC_CLIENT:true}
keycloak.ssl-required=${KEYCLOAK_SSL_REQUIRED:external}
app.keycloak.grant-type=${APP_KEYCLOAK_GRANT_TYPE:password}
app.keycloak.scope=${APP_KEYCLOAK_SCOPE:openid, profile}
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.resource=${KEYCLOAK_RESOURCE}
keycloak.realm=${KEYCLOAK_REALM}
app.keycloak.client-id=${APP_KEYCLOAK_CLIENT_ID:${keycloak.resource}}
app.keycloak.client-secret=${APP_KEYCLOAK_CLIENT_SECRET}
app.keycloak.authServerUrl=${APP_KEYCLOAK_AUTH_SERVER_URL:${keycloak.auth-server-url}}
app.keycloak.refresh=${APP_KEYCLOAK_REFRESH:/realms/botswana-emr-realm/protocol/openid-connect/token}
app.keycloak.realm.username=${APP_KEYCLOAK_REALM_USERNAME:admin}
app.keycloak.realm.password=${APP_KEYCLOAK_REALM_PASSWORD}
keycloak.confidential-port=${KEYCLOAK_CONFIDENTIAL_PORT:443}
keycloak.use-resource-role-mappings=${KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS:true}
keycloak.bearer-only=${KEYCLOAK_BEARER_ONLY:true}
keycloak.disable-trust-manager=${KEYCLOAK_DISABLE_TRUST_MANAGER:true}
server.error.include-message=${SERVER_ERROR_INCLUDE_MESSAGE:always}

notification=${NOTIFICATION_SERVICE_URL}