server.port=7002
spring.application.name=botswanaambulance

spring.profiles.active=server

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)

#Keycloak
keycloak.ssl-required = external
app.keycloak.grant-type=password
app.keycloak.scope=openid, profile


app.keycloak.client-secret=LtpCwXs8J2YHxEAFN2hc2sI6CfLHPNjB
keycloak.auth-server-url =http://keycloak:8080/
app.keycloak.authServerUrl =http://keycloak:8080/

keycloak.resource =botswana-emr
keycloak.realm =botswana-emr-realm
app.keycloak.client-id =${keycloak.resource}

app.keycloak.realm.username=admin
app.keycloak.realm.password=adminpass

keycloak.confidential-port=443

keycloak.use-resource-role-mappings = true
#The line below will prevent redirect to login page
keycloak.bearer-only = true
keycloak.disable-trust-manager=true

