## Microservice Properties
notification =http://0.0.0.0:7001
authentication =http://0.0.0.0:8081

spring.jpa.hibernate.ddl-auto = create-drop
spring.datasource.username=intellisoft
spring.datasource.password=Sc281-6736/2014
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.url=jdbc:postgresql://localhost:5467/bitri_ambulance