## Microservice Properties
authentication =http://172.105.157.130:8081/auths
notification = http://172.105.157.130:7001/notification

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:postgresql://172.105.157.130:5432/bitri_ambulance
spring.datasource.username=intellisoft
spring.datasource.password=Sc281-6736/2014
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=1
