spring.profiles.active=${FILESTORAGE_SPRING_PROFILES_ACTIVE:prod}

logging.level.org.hibernate.SQL= DEBUG
spring.servlet.multipart.enabled=${FILESTORAGE_SPRING_SERVLET_MULTIPART_ENABLED:true}

spring.servlet.multipart.file-size-threshold=${FILESTORAGE_SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD:2KB}
spring.servlet.multipart.max-file-size=${FILESTORAGE_SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:1000MB}
spring.servlet.multipart.max-request-size=${FILESTORAGE_SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:125MB}

file.upload-dir=${FILESTORAGE_FILE_UPLOAD_DIR:/var/www/upload/}
server.port=${FILESTORAGE_FILE_STORAGE_SERVER_PORT:7003}

springdoc.swagger-ui.disable-swagger-default-url=true
api.response-codes.ok.desc=OK
api.response-codes.badRequest.desc=BAD_REQUEST
api.response-codes.notFound.desc=NOT_FOUND