## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=${NOTIFICATIONS_SPRING_DATASOURCE_URL}
spring.datasource.hikari.maximum-pool-size=${NOTIFICATIONS_SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${NOTIFICATIONS_SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}
spring.datasource.username=${NOTIFICATIONS_SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${NOTIFICATIONS_SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql=true

server.port=${NOTIFICATIONS_SERVER_PORT}
spring.application.name=${NOTIFICATIONS_SPRING_APPLICATION_NAME}

