spring.profiles.active=${SPRING_PROFILES_ACTIVE:server}

## Keycloak Config
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.resource=${KEYCLOAK_RESOURCE}
keycloak.realm=${KEYCLOAK_REALM}
app.keycloak.client-secret=${APP_KEYCLOAK_CLIENT_SECRET}
keycloak.use-resource-role-mappings=${KEYCLOAK_USE_RESOURCE_ROLE_MAPPINGS:true}
#The line below will prevent redirect to login page
keycloak.bearer-only=${KEYCLOAK_BEARER_ONLY:true}


keycloak.disable-trust-manager=${KEYCLOAK_DISABLE_TRUST_MANAGER:true}
authentication=${AUTHENTICATION_SERVICE_URL}
notification=${NOTIFICATION_SERVICE_URL}


#mail sender
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

