server.port=7001
spring.application.name=botswananotification

spring.profiles.active=server

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format.sql = true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:postgresql://172.105.157.130:5432/bitri_notifications
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.username=intellisoft
spring.datasource.password=Sc281-6736/2014
spring.jpa.show-sql=true

## Keycloak Config
keycloak.auth-server-url =http://keycloak:8080/
keycloak.resource =botswana-emr
keycloak.realm =botswana-emr-realm
app.keycloak.client-secret=LtpCwXs8J2YHxEAFN2hc2sI6CfLHPNjB
keycloak.use-resource-role-mappings = true
#The line below will prevent redirect to login page
keycloak.bearer-only = true


keycloak.disable-trust-manager=true
authentication =http://172.105.157.130:8081/auths
notification = http://172.105.157.130:7001/notification


#mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=botswanaemr@gmail.com
spring.mail.password=zvwmevsebljjnawy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

